1.You are given two strings s and t. String t is generated by randomly shuffling string s and then adding one more letter at a random position. Return the letter that was added to t.

Examples

find_the_difference("abcd", "abcde") ➞ "e"

find_the_difference("", "y") ➞ "y"

find_the_difference("ae", "aea") ➞ "a"

In [11]:
def find_the_difference(s,r):
  l1 = list(s)
  l2 = list(r)
  l3 = [i for i in l1+l2 if i not in l1 or i not in l2]
  return "".join(l3) 
print(find_the_difference("abcd","abcde"))
print(find_the_difference("", "y"))

e
y

2.Given a function that accepts unlimited arguments, check and count how many data types are in those arguments. Finally return the total in a list.

List order is:

[int, str, bool, list, tuple, dictionary]

Examples

count_datatypes(1, 45, "Hi", False) ➞ [2, 1, 1, 0, 0, 0]

count_datatypes([10, 20], ("t", "Ok"), 2, 3, 1) ➞ [3, 0, 0, 1, 1, 0]

count_datatypes("Hello", "Bye", True, True, False, {"1": "One", "2": "Two"}, [1, 3], {"Brayan": 18}, 25, 23) ➞ [2, 2, 3, 1, 0, 2]

count_datatypes(4, 21, ("ES", "EN"), ("a", "b"), False, [1, 2, 3], [4, 5, 6]) ➞ [2, 0, 1, 2, 2, 0]

In [13]:
def count_datatypes(*args):
  l1=[]
  int_count=0
  str_count=0
  bool_count=0
  list_count=0
  tuple_count=0
  dict_count=0
  for i in args:
    if type(i)==int:
      int_count+=1
    elif type(i)==str:
      str_count+=1
    elif type(i)==bool:
      bool_count+=1
    elif type(i)==list:
      list_count+=1
    elif type(i)==tuple:
      tuple_count+=1
    elif type(i)==dict:
      dict_count+=1
  l1.append(int_count)
  l1.append(str_count)
  l1.append(bool_count)
  l1.append(list_count)
  l1.append(tuple_count)
  l1.append(dict_count)
  return l1

print(count_datatypes(1, 45, "Hi", False))
print(count_datatypes([10, 20], ("t", "Ok"), 2, 3, 1))
print(count_datatypes("Hello", "Bye", True, True, False, {"1": "One", "2": "Two"}, [1, 3], {"Brayan": 18}, 25, 23))
print(count_datatypes(4, 21, ("ES", "EN"), ("a", "b"), False, [1, 2, 3], [4, 5, 6]))

[2, 1, 1, 0, 0, 0]
[3, 0, 0, 1, 1, 0]
[2, 2, 3, 1, 0, 2]
[2, 0, 1, 2, 2, 0]

3.A Fibonacci string is a precedence of the Fibonacci series. It works with any two characters of the English alphabet (as opposed to the numbers 0 and 1 in the Fibonacci series) as the initial items and concatenates them together as it progresses in a similar fashion as the Fibonacci series.

Examples

fib_str(3, ["j", "h"]) ➞ "j, h, hj"

fib_str(5, ["e", "a"]) ➞ "e, a, ae, aea, aeaae"

fib_str(6, ["n", "k"]) ➞ "n, k, kn, knk, knkkn, knkknknk"

In [16]:
def fib_str(n,l1):
  l2=[]
  a=l1[0]
  b=l1[1]
  l2.append(a)
  l2.append(b)
  c=''
  for i in range(2,n):
    c = a+b
    l2.append(c)
    a,b=b,c
  return ",".join(l2)

print(fib_str(3,['j','h']))
print(fib_str(5, ["e", "a"]))
print(fib_str(6, ["n", "k"]))

j,h,jh
e,a,ea,aea,eaaea
n,k,nk,knk,nkknk,knknkknk

4.Given an integer between 0 and 26, make a variable (self.answer). That variable would be assigned to a string in this format:

"nines:your answer, threes:your answer, ones:your answer"

You need to find out how many ones, threes, and nines it would at least take for the number of each to add up to the given integer when multiplied by one, three or nine (depends).

Examples

ones_threes_nines(10) ➞ "nines:1, threes:0, ones:1"

ones_threes_nines(15) ➞ "nines:1, threes:2, ones:0"

ones_threes_nines(22) ➞ "nines:2, threes:1, ones:1"

In [39]:
def ones_threes_nines(num):
  d={"nines":0,"threes":0,"ones":0}
  n=num
  d["nines"]=num//9
  num = num%9
  d["threes"]=num//3
  num = num%3
  d["ones"]=num//1
  return d

print(ones_threes_nines(10))
print(ones_threes_nines(15))
print(ones_threes_nines(22))

{'nines': 1, 'threes': 0, 'ones': 1}
{'nines': 1, 'threes': 2, 'ones': 0}
{'nines': 2, 'threes': 1, 'ones': 1}

5.The Fibonacci sequence is a classic use case for recursive functions since the value of the sequence at a given index is dependent on the sum of the last two values. However, the recursion tree created by solving the Fibonacci sequence recursively can grow quite fast. Therefore it can be important to think about the implications of running a function recursively. Depending on the size of n needed and the capabilities of the system in question you might want to take a different approach.

Write a non-recursive function that takes an integer n and returns the Fibonacci sequence's value at index n.

Examples

fib(6) ➞ 8
0 + 1 = 1, 1 + 1 = 2, 1 + 2 = 3, 2 + 3 = 5, 3 + 5 = 8

fib(1) ➞ 1

fib(2) ➞ 1

In [25]:
def fib_gen(n):
  for i in range(1,n):
    yield i
def fib(n):
  a=0
  b=1
  for i in fib_gen(n):
    c=a+b
    a,b = b,c
  if n == 1:
    return 1
  else:
    return c

print(fib(6))
print(fib(1))
print(fib(2))

8
1
1